<?php
$title = 'Удаление исполнителя';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы действительно хотите удалить?:
    '<?php echo $this->escapeHtml($album->title); ?>'
    '<?php echo $this->escapeHtml($album->artist); ?>'
</p>
<?php
$url = $this->url('album', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>"/>
        <input type="submit" name="del" value="Да" class="btn btn-primary"/>
        <input type="submit" name="del" value="Нет" class="btn btn-primary"/>
    </div>
</form>