<?php
$title = 'Cписок исполнителей';
$album = null;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Добавить новый список</a>
</p>

<table class="table table-hover">
    <tr>
        <th>Название</th>
        <th>Артист</th>
        <th>Действие</th>
    </tr>
    <?php foreach ($albums as $album) :?>

        <tr>
            <td><?php echo $this->escapeHtml($album->title)?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url('album',array('action'=>'edit', 'id' => $album->id));?>">Редактировать</a>
                <a href="<?php echo $this->url('album',array('action'=>'delete', 'id' => $album->id));?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php if(is_null($album)):?>
        <tr>
            <td colspan='3'><p class="lead">Список пуст</p></td>
        </tr>
    <?php endif;?>
</table>
